parameters:
#    ap_backend.example.class: Ap\BackendBundle\Example

services:
#    ap_backend.example:
#        class: %ap_backend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
